### ISSUE TITLE
Dialog tweaks

### ISSUE THREAD

**Issue by delaneyj** [garth/snabbdom-material#19]
1.  Cancel shouldn't be the a primary color, only the confirm button.
2.  Should the buttons be more generic whereas its more about proper placement at bottom of dialog?  (ie what if you want more than 2 buttons or to control the styling, relates to #1)
3.  If the buttons are fixed they should have default ok/cancel labels.
4.  Setting width||height to something like '90%' offsets but does not expand the dialog contents

**Comment by garth** [comment]
1. Fix coming
2. If you don't supply data for buttons then you can manually add any content you wish as part of children.
3. Buttons are not fixed, so you can leave them out and the will not appear.
4. All sizing in in pixels and should be provided as numbers since internally the components are doing math on the number.

**Comment by garth** [comment]
Styling of secondary button font colour may sometimes clash with the background colour. This will be addressed with #9.
